# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "777777777777777"
  tag: "v1.0.5-f6ae942"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
serviceAccount:
  create: true
  name: my-service-account
service:
  port: 80
